// Indian brand name → generic name mapping
// Combination drugs use the format: "drug1 + drug2"
// Keys are lowercase for case-insensitive matching

const indianBrands = {

  // ── Analgesics / Antipyretics ─────────────────────────────────────────────
  "dolo":                   "paracetamol",
  "dolo 650":               "paracetamol",
  "dolo 500":               "paracetamol",
  "crocin":                 "paracetamol",
  "crocin 650":             "paracetamol",
  "calpol":                 "paracetamol",
  "metacin":                "paracetamol",
  "febrinil":               "paracetamol",
  "pyrigesic":              "paracetamol",

  // ── NSAIDs ────────────────────────────────────────────────────────────────
  "combiflam":              "ibuprofen + paracetamol",
  "brufen":                 "ibuprofen",
  "ibugesic":               "ibuprofen",
  "nurofen":                "ibuprofen",
  "voveran":                "diclofenac",
  "volini":                 "diclofenac",
  "diclomol":               "diclofenac + paracetamol",
  "dynapar":                "diclofenac",
  "hifenac":                "aceclofenac",
  "hifenac p":              "aceclofenac + paracetamol",
  "zerodol":                "aceclofenac",
  "zerodol p":              "aceclofenac + paracetamol",
  "zerodol sp":             "aceclofenac + paracetamol + serratiopeptidase",
  "movon":                  "mefenamic acid + paracetamol",
  "meftal spas":            "mefenamic acid + dicyclomine",
  "meftal forte":           "mefenamic acid + paracetamol",

  // ── Antacids / GI ─────────────────────────────────────────────────────────
  "pan":                    "pantoprazole",
  "pan 40":                 "pantoprazole",
  "pand":                   "pantoprazole + domperidone",
  "pan d":                  "pantoprazole + domperidone",
  "pan-d":                  "pantoprazole + domperidone",
  "nexpro":                 "esomeprazole",
  "nexpro rd":              "esomeprazole + domperidone",
  "nexium":                 "esomeprazole",
  "omez":                   "omeprazole",
  "omez d":                 "omeprazole + domperidone",
  "omez it":                "omeprazole + itopride",
  "rantac":                 "ranitidine",
  "zinetac":                "ranitidine",
  "gelusil":                "aluminium hydroxide + magnesium hydroxide",
  "digene":                 "aluminium hydroxide + magnesium hydroxide",
  "pudin hara":             "mint + activated charcoal",
  "cyclopam":               "dicyclomine + paracetamol",
  "maalox":                 "aluminium hydroxide + magnesium hydroxide",
  "sucrafil":               "sucralfate",
  "rablet":                 "rabeprazole",
  "rablet d":               "rabeprazole + domperidone",
  "razo":                   "rabeprazole",
  "razo d":                 "rabeprazole + domperidone",

  // ── Antibiotics ───────────────────────────────────────────────────────────
  "azithral":               "azithromycin",
  "zithromax":              "azithromycin",
  "azee":                   "azithromycin",
  "augmentin":              "amoxicillin + clavulanic acid",
  "mox":                    "amoxicillin",
  "amoxil":                 "amoxicillin",
  "cifran":                 "ciprofloxacin",
  "ciplox":                 "ciprofloxacin",
  "levoflox":               "levofloxacin",
  "levaquin":               "levofloxacin",
  "taxim":                  "cefotaxime",
  "taxim o":                "cefixime",
  "zifi":                   "cefixime",
  "ceftas":                 "cefpodoxime",
  "monocef":                "ceftriaxone",
  "oflox":                  "ofloxacin",
  "zenflox":                "ofloxacin",
  "o2":                     "ofloxacin + ornidazole",
  "norflox":                "norfloxacin",
  "norflox tz":             "norfloxacin + tinidazole",
  "metrogyl":               "metronidazole",
  "flagyl":                 "metronidazole",
  "tiniba":                 "tinidazole",
  "fasigyn":                "tinidazole",
  "doxycap":                "doxycycline",
  "vibramycin":             "doxycycline",
  "clavam":                 "amoxicillin + clavulanic acid",
  "clindac a":              "clindamycin",

  // ── Antifungals ───────────────────────────────────────────────────────────
  "zocon":                  "fluconazole",
  "forcan":                 "fluconazole",
  "funzela":                "fluconazole",
  "candid":                 "clotrimazole",
  "itaspor":                "itraconazole",
  "sporanox":               "itraconazole",

  // ── Antivirals ────────────────────────────────────────────────────────────
  "zovirax":                "acyclovir",
  "acivir":                 "acyclovir",
  "valcivir":               "valacyclovir",
  "viraday":                "tenofovir + emtricitabine + efavirenz",
  "lamirol":                "lamivudine",

  // ── Cardiovascular ────────────────────────────────────────────────────────
  "ecosprin":               "aspirin",
  "ecosprin av 75":         "aspirin + atorvastatin",
  "ecosprin gold":          "aspirin + atorvastatin + clopidogrel",
  "deplatt":                "clopidogrel",
  "clopivas":               "clopidogrel",
  "storvas":                "atorvastatin",
  "lipitor":                "atorvastatin",
  "atorva":                 "atorvastatin",
  "rozavel":                "rosuvastatin",
  "crestor":                "rosuvastatin",
  "rosuvas":                "rosuvastatin",
  "stamlo":                 "amlodipine",
  "amlip":                  "amlodipine",
  "norvasc":                "amlodipine",
  "met xl":                 "metoprolol",
  "metolar":                "metoprolol",
  "atenolol":               "atenolol",
  "tenormin":               "atenolol",
  "cardace":                "ramipril",
  "hopace":                 "ramipril",
  "coversyl":               "perindopril",
  "telma":                  "telmisartan",
  "telma h":                "telmisartan + hydrochlorothiazide",
  "telma am":               "telmisartan + amlodipine",
  "telmikind":              "telmisartan",
  "losartan":               "losartan",
  "losar h":                "losartan + hydrochlorothiazide",
  "olmesar":                "olmesartan",
  "betaloc":                "metoprolol",
  "sorbitrate":             "isosorbide dinitrate",
  "nitrolong":              "isosorbide mononitrate",
  "minipress":              "prazosin",
  "digoxin":                "digoxin",
  "lanoxin":                "digoxin",
  "lasix":                  "furosemide",
  "frusemide":              "furosemide",

  // ── Diabetes ──────────────────────────────────────────────────────────────
  "glycomet":               "metformin",
  "glucophage":             "metformin",
  "glycomet gp1":           "metformin + glimepiride",
  "glycomet gp2":           "metformin + glimepiride",
  "amaryl":                 "glimepiride",
  "glimestar":              "glimepiride",
  "januvia":                "sitagliptin",
  "vildagliptin":           "vildagliptin",
  "galvus":                 "vildagliptin",
  "galvus met":             "vildagliptin + metformin",
  "jardiance":              "empagliflozin",
  "forxiga":                "dapagliflozin",
  "invokana":               "canagliflozin",
  "ozempic":                "semaglutide",
  "victoza":                "liraglutide",
  "lantus":                 "insulin glargine",
  "tresiba":                "insulin degludec",
  "novorapid":              "insulin aspart",
  "actrapid":               "insulin soluble",
  "mixtard":                "insulin isophane + insulin soluble",

  // ── Respiratory ───────────────────────────────────────────────────────────
  "asthalin":               "salbutamol",
  "ventolin":               "salbutamol",
  "levolin":                "levosalbutamol",
  "foracort":               "formoterol + budesonide",
  "seroflo":                "salmeterol + fluticasone",
  "budecort":               "budesonide",
  "flohale":                "fluticasone",
  "montek":                 "montelukast",
  "montair":                "montelukast",
  "montek lc":              "montelukast + levocetirizine",
  "singulair":              "montelukast",
  "tiova":                  "tiotropium",
  "spiriva":                "tiotropium",
  "alex":                   "levosalbutamol + ambroxol + guaifenesin",
  "ascoril":                "salbutamol + bromhexine + guaifenesin",
  "benadryl":               "diphenhydramine",
  "corex":                  "chlorpheniramine + codeine",

  // ── Antihistamines / Allergy ──────────────────────────────────────────────
  "cetirizine":             "cetirizine",
  "alerid":                 "cetirizine",
  "cetzine":                "cetirizine",
  "zyrtec":                 "cetirizine",
  "levocet":                "levocetirizine",
  "xyzal":                  "levocetirizine",
  "atarax":                 "hydroxyzine",
  "allegra":                "fexofenadine",
  "telekast l":             "montelukast + levocetirizine",

  // ── Steroids ──────────────────────────────────────────────────────────────
  "wysolone":               "prednisolone",
  "omnacortil":             "prednisolone",
  "medrol":                 "methylprednisolone",
  "depo medrol":            "methylprednisolone",
  "dexamethasone":          "dexamethasone",
  "decadron":               "dexamethasone",
  "betnesol":               "betamethasone",

  // ── Thyroid ───────────────────────────────────────────────────────────────
  "eltroxin":               "levothyroxine",
  "thyronorm":              "levothyroxine",
  "thyrox":                 "levothyroxine",
  "neomercazole":           "carbimazole",

  // ── Neurological / Psychiatric ────────────────────────────────────────────
  "eptoin":                 "phenytoin",
  "dilantin":               "phenytoin",
  "valparin":               "sodium valproate",
  "encorate":               "sodium valproate",
  "oxetol":                 "oxcarbazepine",
  "trileptal":              "oxcarbazepine",
  "frisium":                "clobazam",
  "urbanol":                "clobazam",
  "lonazep":                "clonazepam",
  "rivotril":               "clonazepam",
  "zapiz":                  "clonazepam",
  "alprax":                 "alprazolam",
  "restyl":                 "alprazolam",
  "xanax":                  "alprazolam",
  "nexito":                 "escitalopram",
  "stalopam":               "escitalopram",
  "lexapro":                "escitalopram",
  "flunil":                 "fluoxetine",
  "prodep":                 "fluoxetine",
  "prozac":                 "fluoxetine",
  "sertraline":             "sertraline",
  "serta":                  "sertraline",
  "zoloft":                 "sertraline",
  "venlor":                 "venlafaxine",
  "effexor":                "venlafaxine",
  "mirtaz":                 "mirtazapine",
  "amitone":                "amitriptyline",
  "tryptomer":              "amitriptyline",
  "sizopin":                "clozapine",
  "clozaril":               "clozapine",
  "oleanz":                 "olanzapine",
  "olimelt":                "olanzapine",
  "risnia":                 "risperidone",
  "risperdal":              "risperidone",
  "haloperidol":            "haloperidol",
  "serenace":               "haloperidol",
  "lithosun":               "lithium",
  "prothiaden":             "dosulepin",
  "risdone":                "risperidone",
  "qutan":                  "quetiapine",
  "seroquel":               "quetiapine",
  "gabapentin":             "gabapentin",
  "gabapin":                "gabapentin",
  "neurontin":              "gabapentin",
  "pregabalin":             "pregabalin",
  "lyrica":                 "pregabalin",
  "pregalin":               "pregabalin",

  // ── Pain / Musculoskeletal ────────────────────────────────────────────────
  "ultracet":               "tramadol + paracetamol",
  "tramazac":               "tramadol + paracetamol",
  "nucoxia":                "etoricoxib",
  "arcoxia":                "etoricoxib",
  "celebrex":               "celecoxib",
  "myospaz":                "chlorzoxazone + paracetamol",
  "flexon":                 "ibuprofen + paracetamol",
  "dolowin":                "nimesulide + paracetamol",
  "nimulid":                "nimesulide",

  // ── Vitamins / Supplements ────────────────────────────────────────────────
  "becosules":              "vitamin b complex",
  "neurobion":              "vitamin b1 + b6 + b12",
  "methylcobal":            "methylcobalamin",
  "mecobal":                "methylcobalamin",
  "shelcal":                "calcium + vitamin d3",
  "calcirol":               "cholecalciferol",
  "uprise d3":              "cholecalciferol",
  "zincovit":               "zinc + multivitamins",
  "ocuvit":                 "lutein + zeaxanthin + vitamins",
  "evion":                  "vitamin e",
  "limcee":                 "vitamin c",
  "feronia xt":             "ferrous ascorbate + folic acid",
  "orofer xt":              "iron + folic acid",

  // ── Oncology ─────────────────────────────────────────────────────────────
  "tamodex":                "tamoxifen",
  "nolvadex":               "tamoxifen",
  "femara":                 "letrozole",
  "letoval":                "letrozole",
  "casodex":                "bicalutamide",
  "arimidex":               "anastrozole",
  "gleevec":                "imatinib",
  "glivec":                 "imatinib",

  // ── Dermatology ──────────────────────────────────────────────────────────
  "betnovate":              "betamethasone",
  "lobate":                 "clobetasol",
  "dermovate":              "clobetasol",
  "eumosone":               "clobetasol",
  "tenovate":               "clobetasol",
  "soframycin":             "framycetin",
  "neosporin":              "neomycin + polymyxin b + bacitracin",
  "fusiderm":               "fusidic acid",
  "candid b":               "clotrimazole + beclomethasone",
  "quadriderm":             "beclomethasone + clotrimazole + neomycin + tolnaftate",

  // ── Antiparasitic ─────────────────────────────────────────────────────────
  "albendazole":            "albendazole",
  "zentel":                 "albendazole",
  "bandy":                  "albendazole",
  "mebex":                  "mebendazole",
  "ivermectin":             "ivermectin",
  "ivecop":                 "ivermectin",
  "scavista":               "ivermectin",

  // ── Urological ────────────────────────────────────────────────────────────
  "urimax":                 "tamsulosin",
  "urimax d":               "tamsulosin + dutasteride",
  "veltam":                 "tamsulosin",
  "dutas":                  "dutasteride",
  "avodart":                "dutasteride",
  "finpecia":               "finasteride",
  "propecia":               "finasteride",

  // ── Hormones / Women's Health ─────────────────────────────────────────────
  "ipill":                  "levonorgestrel",
  "unwanted 72":            "levonorgestrel",
  "primolut n":             "norethisterone",
  "duphaston":              "dydrogesterone",
  "susten":                 "progesterone",
  "ovral l":                "ethinylestradiol + levonorgestrel",
  "loette":                 "ethinylestradiol + levonorgestrel",
  "yasmin":                 "ethinylestradiol + drospirenone",
  "clomid":                 "clomiphene",
  "siphene":                "clomiphene",

  // ── Miscellaneous ─────────────────────────────────────────────────────────
  "drotin":                 "drotaverine",
  "buscopan":               "hyoscine butylbromide",
  "ondem":                  "ondansetron",
  "emeset":                 "ondansetron",
  "perinorm":               "metoclopramide",
  "reglan":                 "metoclopramide",
  "stemetil":               "prochlorperazine",
  "vertin":                 "betahistine",
  "stugeron":               "cinnarizine",
  "unienzyme":              "fungal diastase + papain",
  "cremaffin":              "liquid paraffin + milk of magnesia",
  "dulcoflex":              "bisacodyl",
  "dulcolax":               "bisacodyl",
  "kayam churna":           "herbal laxative",
  "ors":                    "oral rehydration salts",
  "electral":               "oral rehydration salts",
};

module.exports = indianBrands;